### PR TITLE
FIX: fix inversion bug in examples/scan-discover.c

### PR DESCRIPTION
**Pull request by panta**

### CODE REVIEW

**Review by br101 — COMMENTED** [review]
Hmm, i believe that 18 bytes should be enough for a MAC address, which is 17 characters + one NULL byte:

```
11:22:33:44:55:66
123456789012345678
```

**Comment by br101** [comment]
apart of my doubt with the string length, looks good! thanks for the pull request

**Comment by panta** [comment]
> Hmm, i believe that 18 bytes should be enough for a MAC address, which is 17 characters + one NULL byte:
> 
> ```
> 11:22:33:44:55:66
> 123456789012345678
> ```

yes, you are absolutely right, sorry!
I'll remove the commit.

**Comment by br101** [comment]
Thanks a lot for the inversion bug! I have already spent some time  to debug it and could not figure it out... I always thought in C array[x][y] is the same as array[y][x]...

**Comment by br101** [comment]
Had to fixup snprintf usage though. it needs the full buffer size. Otherwise i get the following warning

../blzlib_util.h:22:17: warning: ‘snprintf’ output truncated before the last format character [-Wformat-truncation=]
   22 | #define MAC_FMT "%02x:%02x:%02x:%02x:%02x:%02x"
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../blzlib_util.c:36:31: note: in expansion of macro ‘MAC_FMT’
   36 |  snprintf(buf, sizeof(buf)-1, MAC_FMT, MAC_PARR(mac));
      |                               ^~~~~~~
../blzlib_util.h:22:47: note: format string is defined here
   22 | #define MAC_FMT "%02x:%02x:%02x:%02x:%02x:%02x"
      |                                               ^
../blzlib_util.c:36:2: note: ‘snprintf’ output 18 bytes into a destination of size 17
   36 |  snprintf(buf, sizeof(buf)-1, MAC_FMT, MAC_PARR(mac));
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by panta** [comment]
> Thanks a lot for the inversion bug! I have already spent some time to debug it and could not figure it out... I always thought in C array[x][y] is the same as array[y][x]...

perhaps you've seen the (surprising!) equivalence `array[a] == a[array]`, but for multi-dimensional arrays the indexes are not equivalent. C and C++ use [row-major ordering](https://en.wikipedia.org/wiki/Row-_and_column-major_order) for multidimensional arrays.

**Comment by panta** [comment]
> Had to fixup snprintf usage though. it needs the full buffer size. Otherwise i get the following warning
> 
> ../blzlib_util.h:22:17: warning: ‘snprintf’ output truncated before the last format character [-Wformat-truncation=]
> 22 | #define MAC_FMT "%02x:%02x:%02x:%02x:%02x:%02x"
> | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../blzlib_util.c:36:31: note: in expansion of macro ‘MAC_FMT’
> 36 | snprintf(buf, sizeof(buf)-1, MAC_FMT, MAC_PARR(mac));
> | ^~~~~~~
> ../blzlib_util.h:22:47: note: format string is defined here
> 22 | #define MAC_FMT "%02x:%02x:%02x:%02x:%02x:%02x"
> | ^
> ../blzlib_util.c:36:2: note: ‘snprintf’ output 18 bytes into a destination of size 17
> 36 | snprintf(buf, sizeof(buf)-1, MAC_FMT, MAC_PARR(mac));
> | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ah, probably the compiler considers (rightfully so) also the terminating NUL byte as part of the format string.

**Comment by br101** [comment]
Thank you!

**Pull request merged**
